---
title: "P13) Research the dissemination and implementation of methods"
link-citations: true
---
Alternative labels: methodological implementation science

## Definition and typical features 
These studies support and evaluate the dissemination and (de-)implementation of methods in health research practice. They assess implementation, identify barriers and facilitators, develop strategies for dissemination and implementation, and test the effectiveness of these strategies.

This type of methods research is still rare. Examples come mostly from areas of reporting guidelines and core outcome sets. Different approaches are possible:

## Boundaries to related purposes

## Typical approaches and corresponding examples 
[Quantitative survey](../approaches/6survey.qmd): Survey of researchers to identify barriers to the implementation of new statistical methods.[@Pullenayegum2016knowledge]

[Qualitative study involving researchers or other interest-holders in health research](../approaches/7qualitative.qmd): interviews with trial investigators why they did not use existing core outcome sets;[@Hughes2022in-depth] survey of investigators in sports medicine why they did not use a specific reporting guideline.[@Hansford2024barriers]

[Review of applied methods](../approaches/9review-applied.qmd): proportion of trials using core outcome sets.[@Matvienko-Sikar2022use]

## Guidance
- Guidance for understanding and applying methods: [REF]
- Guidance for reporting methods: [REF]
- Guidance for assessing methods: [REF]
