---
title: "9 Develop guidance for applying methods"
link-citations: true
---
Alternative labels: methods guidance; tutorial; best practice recommendations

## Definition 
These studies develop guidance to help health researchers or other interest holders understand and apply methods. The guidance may include conceptual explanations, examples, recommendations for or against specific methods, or tools that operationalize guidance aids such as decision algorithms, step-by-step tutorials, templates, or code for statistical software. The development process may combine multiple approaches of methods research.

## Typical approaches and corresponding examples 
Approaches to develop methods guidance greatly vary and include: [Theory-based methods research](../approaches/1theory.qmd): Covariate adjustment in trials;[@VanLancker2024covariate] credibility criteria for subgroup effects, some criteria based on theoretical reasoning.[@Schandelmaier2020development]

[Simulation study](../approaches/2simulation.qmd): Guidance on using matching in cluster trials; [@Chondros2021when] Guidance for variable screening in high dimensional survival analysis; [@Edelmann2020marginal] estimation of diagnostic test accuracy without reference standard.[@Sun2025estimation]

[Experimental analysis of real datasets](../approaches/3real-datasets.qmd): Guidance for using machine learning for abstract screening; [@Hamel2021guidance] Framework for prospective meta-analysis, tested in 4 real projects.[@Tierney2021a]

[Qualitative study involving researchers or other interest-holders in health research](../approaches/7qualitative.qmd): Q-methodology, focus groups, content analysis, and workshops to produce guidance on creating summaries for trial participants.[@Bruhn2022what]

[Consensus study among researchers or other interest-holders in health research](../approaches/8consensus.qmd): Guidance on factors to consider when inviting multiple interest-holder groups to research, based on Delphi; [@Parker2022factors] Guidance on handling missing data in trials, based on Nominal Group Technique.[@Hussain2022development]

[Review of applied methods](../approaches/9review-applied.qmd): recommendations for the use of directed acyclic graphs.[@Tennant2021use]

[Scoping review of methods research](../approaches/11scoping-review.qmd): A scoping review of methods papers informed guidance on integrating qualitative methods in randomized trials of complex interventions;[@Davis2019beyond] A scoping review of methods papers informed guidance for developing core outcome sets.[@Prinsen2016how]

[Qualitative synthesis of methods research](../approaches/12qualitative-synthesis.qmd): Review with qualitative synthesis of guidance for the evaluation and updating of clinical prediction models;[@Binuya2022methodological] review of methods research on saturation in qualitative studies;[@Hennink2022sample] review of methods for confidence intervals in adaptive trials.[@Robertson2025confidence]

[Informal approaches](../approaches/15informal.qmd): preventing common misunderstandings of randomisation;[@Senn2013seven] tutorial for sample size calculation in cluster trials;[@Hemming2020a] explanation why guidelines should seldom make good practice statements.[@Guyatt2016guideline]

## Guidance
- Guidance for understanding and applying methods: [REF]
- Guidance for reporting methods: [REF]
- Guidance for assessing methods: [REF]
