project:
  type: book
  output-dir: docs

book:
  title: "Guide to Methods Research"

  chapters:
    - index.qmd

    - part: Foundations
      chapters:
        - foundations/intro.qmd

    - part: Types of Methods Research
      chapters:
        - types/theory.qmd
        - types/simulation.qmd

    - part: Guidance
      chapters:
        - guidance/conducting.qmd
        - guidance/reporting.qmd

format:
  html:
    theme: cosmo