---
title: "About this initiative"
---

Welcome! 

This website is under construction. It will soon host the new **Typology of Methods Research (TYPE-ME)** - a living resource for methods research who work in the context of health research and pysychology. The typology is based on an [ongoing consensus study](https://osf.io/4fxaz/overview).

Once the typology is ready, we plan the following next steps: 

- Collect existing guidance for each type. 
- By and by, develop new guidance where needed
- Add community features to collect and document user-feedback

You are invited to explore the current prototype:

# The typology

## Definitions and scope
methodological research (MR) aims to develop, evaluate, refine, guide, or (de-)implement research methods, or synthesize existing MR. 

The targets of MR are research methods across the whole research lifecycle, including the methods for planning (e.g., formulating research questions or determining sample size), conducting (e.g., recruiting participants or collecting measurements), analyzing and interpreting (e.g., statistical or qualitative analysis), reporting (e.g., reporting checklists or journal standards), summarizing (e.g., systematic reviews), evaluating (e.g., risk of bias tools or peer review), and implementing research (e.g., clinical practice guidelines or decision aids). 

In addition to research methods, MR also addresses the underlying research challenges that demand methodological solutions (e.g., missing data or conflicts of interest) and the consequences of methodological choices (e.g., biases in observational studies or limitations of significance thresholds for p-values).

For this typology, we narrowed the scope to MR on research methods used in health research.
Possible applications of the typology

## Detailed version

In the detailed version, we defined methodological study types along two broad dimensions: by approach (“What are the different ways in which we can answer methodological research questions?”), which includes 15 types (Table 1), and by purpose (“What are the different objectives or research questions of MR?”), which includes 13 types (Table 2). For each type, we suggest preferred and alternative terms, provide a definition, boundary notes, and show examples. Technically, the detailed typology is a faceted taxonomy with two facets corresponding to the two dimensions approach and purpose. In this manuscript, we present the two facets in separate tables while the website provides a more interactive format that allows collapsing and expanding of details.

The two dimensions are cross-cutting because one approach can serve several purposes and one purpose can draw on different approaches. For example, the approach “review of applied methods” can serve the purposes “describe current practice”, “identify the need for new methods”, or “evaluate the implementation of methods”. An example from the purpose domain is “development of methods guidance”, for which one can consider input from various approaches such as a systematic review of MR, qualitative studies involving interest-holders, or a consensus study. To make this cross-cutting structure explicit, the tables provide for each approach examples of typical purposes and for each purpose examples of typical approaches in the 3rd column

The ordering of approaches does not impose a hierarchy of strength, such as progression from “weak” to “strong” approaches. While some approaches may, in certain contexts, advance understanding in a more compelling way than another, rather than a linear journey, the typology describes a research ecosystem - a house with many interconnecting rooms of different types. The ordering of purposes broadly reflects the lifecycle of a method,(Heinze2024) beginning with assessing the status quo and research needs and ending with de-implementing methods that researchers should no longer use.

Browse the two dimension using the following links or the side bar. 

**Approaches**

- [A1) Theory-based methods research](theory.qmd)
- [A2) Simulation study](simulation.qmd)
- [A3) Experimental analysis of real datasets](real-datasets.qmd)
- [A4) Methodological randomized study](randomized.qmd)
- [A5) Reliability and agreement studies](reliability.qmd)
- [A6) Quantitative survey involving researchers and other interest-holders in health research](quantitative-survey.qmd)
- [A7) Qualitative study involving researchers or other interest-holders in health research](qualitative-study.qmd)
- [A8) Consensus study among researchers or other interest-holders in health research](consensus.qmd)
- [A9) Review of applied methods](review-applied-methods.qmd)
- [A10) Meta-epidemiological study](meta-epidemiological.qmd)
- [A11) Scoping review of methods research](scoping-review-mr.qmd)
- [A12) Qualitative synthesis of methods research](qualitative-synthesis.qmd)
- [A13) Quantitative synthesis of methods research](quantitative-synthesis.qmd)
- [A14) Methodological case report or series](case-report.qmd)
- [A15) Informal approaches](informal.qmd)

**purposes**

- [P1) Identify available methods](identify-methods.qmd)
- [P2) Identify available methods research on a specific topic](identify-mr-topic.qmd)
- [P3) Summarize the results of methods research](summarize-mr.qmd)
- [P4) Assess methodological practice](assess-practice.qmd)
- [P5) Assess needs and priorities for methods research](assess-needs-priorities.qmd)
- [P6) Propose a new method](propose-method.qmd)
- [P7) Evaluate a single method](evaluate-method.qmd)
- [P8) Compare two or more methods](compare-methods.qmd)
- [P9) Develop guidance for understanding and applying methods](guidance-understanding-applying.qmd)
- [P10) Develop reporting guidelines](reporting-guidelines.qmd)
- [P11) Develop quality assessment instruments](quality-assessment-instruments.qmd)
- [P12) Develop software and code](software-code.qmd)
- [P13) Research the dissemination and implementation of methods](implementation.qmd)

## Simple version 

The simple version shows a selection of 12 essential study types, mixing types defined by apporoach and purpose, and collapsing some clusters: 

- [Theory-based methods research](theory.qmd)
- [Simulation study](simulation.qmd)
- [Experimental analysis of real datasets](real-datasets.qmd)
- [Methodological randomized study](randomized.qmd)
- [Reliability or agreement study](reliability.qmd)
- Study involving methods users and other interest-holders ([surveys](quantitative-survey.qmd), [qualitative studies](qualitative-study.qmd))
- [Consensus study](consensus.qmd)
- [Review of applied methods](review-applied-methods.qmd)
- [Meta-epidemiological study](meta-epidemiological.qmd)
- Review of methods research ([scoping](scoping-review-mr.qmd), [qualitative](qualitative-synthesis.qmd), [quantitative](quantitative-synthesis.qmd)
- Methods guidance ([applying](guidance-understanding-applying.qmd), [reporting](reporting-guidelines.qmd), [assessing](quality-assessment-instruments.qmd))
- [Methodological implementation science](implementation.qmd)
