---
title: "10 Meta-epidemiological studies"
link-citations: true
---

Terminology: analytical study of applied methods

## Definition and features
In meta-epidemiological studies, researchers examine how variation in methodological practice relates to variation in study results or other study-level outcomes. They draw on similar sources as reviews of applied or planned methods, but treat methodological features as exposures or covariates and study results as outcomes. They often use stratified, matched, or complete samples of studies that applied different methods and analyze associations with meta-regression or multi-level modeling.

- A strength is that these studies reflect real-world applications of methods, including human error.
- A limitation is the high risk of confounding, which can arise at multiple levels, including differences in study populations, research questions, measurement procedures, or other study features.

::: {.callout-tip appearance="minimal" collapse="true"}
## Boundaries with related types
Boundary with A9 reviews of applied or planned methods. Both examine applied studies. A9 describes methodological practice or quality; A10 examines whether methodological features relate to study results.

**Similarities and differences between literature-based types:**

| Characteristic | [Reviews of applied or planned methods](9review-applied.qmd) | [Meta-epidemiological studies](10meta-epi.qmd) | [Scoping reviews of methods research](11scoping-review.qmd) | [Qualitative syntheses of methods research](12qualitative-synthesis.qmd) | [Quantitative syntheses of methods research](13quantitative-synthesis.qmd) |
| :---- | :---- | :---- | :---- | :---- | :---- |
| Typical objective | Assess methodological practice or quality | Assess impact of methodological characteristics on study results | Identify available methods or methods research on a specific topic | Synthesize findings of methods research qualitatively | Synthesize findings of methods research quantitatively |
| Included publications/ unit of analysis | Individual applied studies | Individual applied studies | Methods research papers | Methods research papers | Methods research papers |
| Sampling strategy | Random, purposeful, stratified, matched, complete^a^ | Stratified, matched, complete^a^ | Complete^a^ | Complete^a^, purposeful | Complete^a^ |
| Typical analytic approach | Qualitative categorization and descriptive statistics | Meta-regression or multi-level modeling | Categorization and descriptive statistics | Qualitative synthesis | Meta-analysis |
| Role of quality assessment | Often as an outcome | Possible as an exposure or covariable | Usually not performed | Step in synthesis process^b^ | Step in synthesis process^b^ |
| Analogy in health research | Observational study (prevalence) | Observational study (exposure-outcome) | Scoping review | Qualitative evidence synthesis | Quantitative evidence synthesis|
::: {.small}
^a^Usually based on a comprehensive search process that aims to find all eligible publications as completely as possible.
^b^Quality criteria currently remain unclear for most types of methods research.
:::
:::

## Typical objectives and corresponding examples
[Compare methods](../objectives/8compare-methods.qmd): comparison of treatment effects between trials with and without adequate allocation concealment or blinding.[@Wood2008empirical]

[Develop guidance for understanding and applying methods](../objectives/9guidance-applying.qmd): effects of rapid-review shortcuts informed Cochrane guidance for conducting rapid reviews.[@Garritty2021cochrane]

## Guidance
- Guidance for understanding and applying methods: [to be added]
- Guidance for reporting methods: [to be added]
- Guidance for assessing methods: [to be added]
