---
title: "13 Quantitative syntheses of methods research"
link-citations: true
---

Terminology: quantitative systematic reviews of methods research; meta-analyses of methods research

## Definition and features
In quantitative syntheses of methods research, researchers synthesize quantitative methods research, such as methodological randomized studies or meta-epidemiological studies. They usually start with a focused quantitative question, search for eligible publications (typically aiming for a complete sample), assess study quality, and use meta-analysis or another quantitative synthesis method to combine findings.

- Strengths include transparency and comprehensiveness.
- Key challenges are the difficult search for methods research, the lack of quality criteria for quantitative methods research, and reporting issues.

::: {.callout-tip appearance="minimal" collapse="true"}
## Boundaries with related types
**Similarities and differences between literature-based types:**

| Characteristic | [Reviews of applied or planned methods](9review-applied.qmd) | [Meta-epidemiological studies](10meta-epi.qmd) | [Scoping reviews of methods research](11scoping-review.qmd) | [Qualitative syntheses of methods research](12qualitative-synthesis.qmd) | [Quantitative syntheses of methods research](13quantitative-synthesis.qmd) |
| :---- | :---- | :---- | :---- | :---- | :---- |
| Typical objective | Assess methodological practice or quality | Assess impact of methodological characteristics on study results | Identify available methods or methods research on a specific topic | Synthesize findings of methods research qualitatively | Synthesize findings of methods research quantitatively |
| Included publications/ unit of analysis | Individual applied studies | Individual applied studies | Methods research papers | Methods research papers | Methods research papers |
| Sampling strategy | Random, purposeful, stratified, matched, complete^a^ | Stratified, matched, complete^a^ | Complete^a^ | Complete^a^, purposeful | Complete^a^ |
| Typical analytic approach | Qualitative categorization and descriptive statistics | Meta-regression or multi-level modeling | Categorization and descriptive statistics | Qualitative synthesis | Meta-analysis |
| Role of quality assessment | Often as an outcome | Possible as an exposure or covariable | Usually not performed | Step in synthesis process^b^ | Step in synthesis process^b^ |
| Analogy in health research | Observational study (prevalence) | Observational study (exposure-outcome) | Scoping review | Qualitative evidence synthesis | Quantitative evidence synthesis|
::: {.small}
^a^Usually based on a comprehensive search process that aims to find all eligible publications as completely as possible.
^b^Quality criteria currently remain unclear for most types of methods research.
:::
:::

## Typical objectives and corresponding examples
[Summarize the results of methods research](../objectives/3summarize-mr.qmd): meta-analysis of comparisons between machine learning and logistic regression for clinical prediction models;[@Christodoulou2019a] meta-analysis of meta-epidemiological studies assessing the impact of blinding in trials;[@Wang2024compelling] meta-analysis of randomized studies comparing blinded versus unblinded risk of bias assessment.[@Morissette2011blinded]

## Guidance
- Guidance for understanding and applying methods: [to be added]
- Guidance for reporting methods: [to be added]
- Guidance for assessing methods: [to be added]
