---
title: "2 Simulation study"
link-citations: true
---

Alternative labels: in silico study

## Definition and typical features 
Simulation studies experimentally apply one or more methods to a large number of simulated datasets. The datasets mimic studies and are generated under specified assumptions, usually with some element of randomness. Software then systematically applies the method(s) under investigation to each dataset to understand how they perform in general. A unique feature and strength is that one can modify the underlying truth, which allows assessing bias and the validity of precision measures under varying conditions. A limitation is that simulated scenarios may not fully capture the complexities of real studies with human error arising during data collection or methods application.

- A unique feature and strength is that one can modify the underlying truth, which allows assessing bias and the validity of precision measures under varying conditions.
- A limitation is that simulated scenarios may not fully capture the complexities of real studies with human error arising during data collection or methods application.

## Boundaries to related types
No related types

## Typical purposes and corresponding examples 
[Propose a new method](../purposes/6propose-method.qmd): new alternative to the log-rank test.[@Magirr2026robust]

[Evaluate a single method](../purposes/7evaluate-method.qmd): random-effects meta-analysis;[@Hartung2001a] false positives when conducting subgroup analysis.[@Brookes2001subgroup]

[Compare two or more methods](../purposes/8compare-methods.qmd): different methods for diagnostic meta-analyses with sparse data;[@Takwoingi2017performance] different methods for modeling multi-state disease progression;[@Huszti2011comparison] comparing two methods for correcting imperfect reference standards in diagnostic accuracy.[@UmemnekuChikere2021comparative]

[Develop guidance for understanding and applying methods](../purposes/9guidance-applying.qmd): Guidance on using matching in cluster trials; [@Chondros2021when] Guidance for variable screening in high dimensional survival analysis; [@Edelmann2020marginal] estimation of diagnostic test accuracy without reference standard.[@Sun2025estimation]

## Guidance
- Guidance for understanding and applying methods: [REF]
- Guidance for reporting methods: [REF]
- Guidance for assessing methods: [REF]
